# Generated by Django 4.2.3 on 2023-08-24 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anketa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anketa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Имя анкеты', max_length=20)),
                ('discription', models.CharField(help_text='Описание анкеты', max_length=20)),
            ],
        ),
    ]
