# Generated by Django 4.2.3 on 2023-08-25 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anketa', '0002_anketa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Имя(название) ответов', max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='anketa',
            name='name',
            field=models.CharField(help_text='Имя(название) анкеты', max_length=20),
        ),
        migrations.CreateModel(
            name='RespondentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='anketa.answer')),
                ('respondent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='anketa.respondent')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Имя(название) вопроса', max_length=20)),
                ('anketa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='anketa.anketa')),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='anketa.question'),
        ),
    ]
